### ISSUE TITLE
cvmfs-scitoken-helper core dumps on RL9

### ISSUE THREAD

**Issue by duncanmmacleod** [cvmfs-contrib/cvmfs-x509-helper#38]
When attempting to use authorised CVMFS (for LIGO) on Rocky Linux 9 the `cvmfs-scitoken-helper` is being reported as core dumping:

```text
Aug 04 09:50:55 datafind-dev cvmfs2[66936]: (ligo.storage.igwn.org) starting authz helper /cvmfs/config-osg.opensciencegrid.org/libexec/authz/cvmfs_scitoken_helper
Aug 04 09:50:55 datafind-dev cvmfs_scitoken_helper[67147]: (ligo.storage.igwn.org) Support for Globus authz is enabled.
Aug 04 09:50:55 datafind-dev cvmfs_scitoken_helper[67147]: (ligo.storage.igwn.org) Failed to load VOMS library; authz will not be available.  libvomsapi.so.1: cannot open shared object file: No such file or directory
Aug 04 09:50:55 datafind-dev cvmfs_scitoken_helper[67147]: (ligo.storage.igwn.org) Support for VOMS authz is NOT enabled.
Aug 04 09:50:55 datafind-dev cvmfs_scitoken_helper[67147]: (ligo.storage.igwn.org) x509 authz helper invoked, connected to cvmfs process 66936
Aug 04 09:50:55 datafind-dev systemd-coredump[67151]: [🡕] Process 67147 (cvmfs_scitoken_) of user 0 dumped core.
Aug 04 09:50:55 datafind-dev cvmfs2[66936]: (ligo.storage.igwn.org) authz helper /cvmfs/config-osg.opensciencegrid.org/libexec/authz/cvmfs_scitoken_helper enters fail state, no more authorization
```

The authz debuglog isn't very helpful:

```text
Successfully loaded Globus library    [08-04-2023 09:50:55 CDT]
Support for Globus authz is enabled.    [08-04-2023 09:50:55 CDT]
Failed to load VOMS library; authz will not be available.  libvomsapi.so.1: cannot open shared object file: No such file or directory    [08-04-2023 09:50:55 CDT]
Support for VOMS authz is NOT enabled.    [08-04-2023 09:50:55 CDT]
x509 authz helper invoked, connected to cvmfs process 66936    [08-04-2023 09:50:55 CDT]
Executable: cvmfs_scitoken_helper    [08-04-2023 09:50:55 CDT]
```

I think @DrDaveD has been able to reproduce this issue on his RL9 system.

<details open>
<summary>Package list</summary>

```console
# dnf list installed | grep -E "cvmfs|x509|voms|osg|token"
cvmfs.x86_64                          2.10.0-1.2.osg36.el9          @osg36
cvmfs-config-osg.noarch               2.5-2.osg36.el9               @osg36
cvmfs-x509-helper.x86_64              2.2-3.osg36.el9               @osg36
frontier-squid.x86_64                 11:5.8-2.1.osg36.el9          @osg36
htgettoken.x86_64                     1.18-1.osg36.el9              @osg36
osg-ca-certs.noarch                   1.112-1.osg36.el9             @osg36
osg-oasis.noarch                      19-2.osg36.el9                @osg36
python3-scitokens.noarch              1.7.0-1.osg36.el9             @osg36
scitokens-cpp.x86_64                  1.0.2-1.el9                   @epel-release
```
</details>

**Comment by DrDaveD** [comment]
I caught a stacktrace by inserting a sleep near the beginning of the program and attaching with gdb:
```
#0  0x00007fb6c9ce454c in __pthread_kill_implementation ()
   from /lib64/libc.so.6
#1  0x00007fb6c9c97d46 in raise () from /lib64/libc.so.6
#2  0x00007fb6c9c6b7f3 in abort () from /lib64/libc.so.6
#3  0x00007fb6c9c6b71b in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007fb6c9c90ce6 in __assert_fail () from /lib64/libc.so.6
#5  0x00005596ad70be72 in Read (buf=0x7ffd7d444540, nbyte=184381)
    at /usr/src/debug/cvmfs-x509-helper-2.2-0.0.20230804164346.vagrant.cd07742fe9d2b34f99c295fd313e0b3664c75957git.el9.x86_64/src/x509_helper.cc:50
#6  0x00005596ad70e36b in ReadMsg ()
    at /usr/src/debug/cvmfs-x509-helper-2.2-0.0.20230804164346.vagrant.cd07742fe9d2b34f99c295fd313e0b3664c75957git.el9.x86_64/src/x509_helper.cc:78
#7  0x00005596ad709e78 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/cvmfs-x509-helper-2.2-0.0.20230804164346.vagrant.cd07742fe9d2b34f99c295fd313e0b3664c75957git.el9.x86_64/src/x509_helper.cc:196
```
